action {
	when {
		and {
			expr {
				match {
					classname: "com/google/security/zynamics/bindiff/gui/tabpanels/TabPanelManager"
				}
			}
		}
	}
	do {
		field_new {
			src_owner: "com/google/security/zynamics/bindiff/gui/tabpanels/TabPanelManager"
			src_name: "WORKSPACE_TAB_COLOR"
		}
	}
}
